redux store data and test
paion-data/nexusgraph pull request #108
Opened 2023-07-10 07:53 UTC by fannifanni

Changelog
---------

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

* [ ] Test
* [ ] Self-review
* [ ] Documentation

2023-07-10 11:32 UTC, QubitPi requested changes
不错！@Xxy1016 指导得很好 @fannifanni 也实现得很到位 <img width="60px" src="https://github.com/paion-data/nexusgraph/assets/16126939/52f8ff92-af23-40ea-897c-1fdb5854457c" />

2023-07-10 11:32 UTC, QubitPi commented on packages/nexusgraph-graph/src/Graph.tsx
这个文件貌似有很大的风格改动，但请 @Xxy1016 看一下是否有逻辑上的变动

2023-07-10 11:32 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.tsx
> -        // TODO - 将图数据送入 Redux Store
![good](https://github.com/paion-data/nexusgraph/assets/16126939/f3cd6d52-30b0-43e0-aea0-69d4601555cd)

2023-07-10 11:32 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.test.tsx
> +test("should handle a todo being added to an empty list", () => {
"`todo`"?<img width="60px" src="https://github.com/paion-data/nexusgraph/assets/16126939/097220ff-6732-4c22-b651-ca688106b7c4" />

2023-07-10 11:32 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.test.tsx
> +test("should handle a todo being added to an existing list", () => {
"`todo`"?<img width="60px" src="https://github.com/paion-data/nexusgraph/assets/16126939/097220ff-6732-4c22-b651-ca688106b7c4" />

2023-07-10 11:50 UTC, QubitPi requested changes

2023-07-10 11:50 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.test.tsx
> +});
最后这三个测试主要是在测试什么？<img width="60px" src="https://github.com/paion-data/nexusgraph/assets/16126939/097220ff-6732-4c22-b651-ca688106b7c4" />

2023-07-11 01:49 UTC, Xxy1016 submitted a review, later dismissed

2023-07-11 02:46 UTC, QubitPi approved these changes

2023-07-11 02:47 UTC, Xxy1016 approved these changes

2023-07-11 03:27 UTC, merged