Add nexusgraph basic e2e test
paion-data/nexusgraph pull request #120
Opened 2023-07-17 10:10 UTC by Xxy1016

Changelog
---------

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

* [ ] Test
* [ ] Self-review
* [ ] Documentation

2023-07-17 11:26 UTC, QubitPi requested changes

2023-07-17 11:26 UTC, QubitPi commented on package.json
> +    "e2e": "cypress run",
`yarn e2e` 需要加到 CI/CD 里面，这个我教你一下

2023-07-17 11:26 UTC, QubitPi commented on tsconfig.json
> +    "types": ["cypress", "node"],
[是因为这个](https://docs.cypress.io/guides/tooling/typescript-support#Configure-tsconfigjson)加上的么？

2023-07-17 11:26 UTC, QubitPi commented on cypress/e2e/nexusgraph.spec.cy.ts
> +  cy.clearAllCookies();
clear cookie 是因为什么？<img width="60px" src="https://github.com/paion-data/nexusgraph/assets/16126939/f67d5ecd-9553-46e1-9a96-b649fa6e61db"/>

2023-07-18 01:10 UTC, Xxy1016 commented on tsconfig.json
> +    "types": ["cypress", "node"],
是的 如果不这样写 cy会报错

2023-07-18 06:04 UTC, QubitPi approved these changes
👍🏻

2023-07-18 06:04 UTC, merged