Logo transform to svg format
paion-data/nexusgraph pull request #146
Opened 2023-08-08 10:19 UTC by Xxy1016

Changelog
---------

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

* [ ] Test
* [ ] Self-review
* [ ] Documentation

2023-08-09 10:00 UTC, fannifanni submitted a review, later dismissed

2023-08-09 12:16 UTC, QubitPi requested changes

2023-08-09 12:20 UTC, QubitPi commented on packages/nexusgraph-app/src/App.tsx
> +            <img src={logo} alt="Logo" width={150} height={150} />
虽然不需要任何修改，但我们需要让 logo 的 size 是[“自适应”](https://stackoverflow.com/a/71948452)的，我开了一个 followup [卡片](https://trello.com/c/6dQyJFVs)来做这个事情，到时候安排合适的人员处理一下即可

2023-08-10 04:22 UTC, fannifanni approved these changes

2023-08-10 06:34 UTC, QubitPi approved these changes

2023-08-10 07:47 UTC, merged