Write text-input document and test
paion-data/nexusgraph pull request #183
Opened 2023-08-25 04:42 UTC by fannifanni

Changelog
---------

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

* [ ] Test
* [ ] Self-review
* [ ] Documentation

2023-08-25 06:25 UTC, QubitPi requested changes

2023-08-25 06:25 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/ui/TextInput.tsx
> +  "data-testid"?: string;
👍🏻

2023-08-25 06:25 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/ui/TextInput.tsx
> + * Implement text input
这个文档写了很久貌似也没写得很具体，下次不懂记得多问，换成这个

```
`TextInput` is a wrapper of [HTML input](https://www.w3schools.com/tags/tag_input.asp) and is used in Editor for various form inputs
```

2023-08-25 06:25 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/ui/TextInput.tsx
> + * @param label The prompt text of the input box
```
@param label  The [label](https://www.w3schools.com/tags/tag_label.asp) for the wrapped <input> element
```

2023-08-25 06:25 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/ui/TextInput.tsx
> + * @param onChange A event function that changes the contents of the input box in real time
`The regular [onChange](https://www.w3schools.com/jsref/event_onchange.asp) callback function that acts on the contents of the input box`

2023-08-25 06:25 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/ui/TextInput.tsx
> + * @param type The type of input
`The type of input` 基本上没有解释什么东西。我们要先通过[文档](https://www.w3schools.com/tags/tag_input.asp)学习 type 是什么东西:

<img width="790" alt="page 1" src="https://github.com/paion-data/nexusgraph/assets/16126939/ad76506b-3561-48ab-84b5-94f4ce47d8f0">

试着再完善一下这一行

2023-08-25 06:25 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/ui/TextInput.test.tsx
> +    render(<TextInput label="my input" value="text in input box" onChange={() => onchange} />);
`{() => onchange}` 里面的 `onchange` 是什么东西？在哪里定义了这个？

2023-08-25 06:25 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/ui/TextInput.test.tsx
> +    expect(screen.getByText("my input")).toBeTruthy();
这个断言想测试什么？

2023-08-28 02:57 UTC, Xxy1016 requested changes

2023-08-28 02:57 UTC, Xxy1016 commented on packages/nexusgraph-editor/src/Lexical/ui/TextInput.test.tsx
测试很完善 👍 不过为了测试更准确也为了确保测试不会因为被后续的代码所影响 所以可以更有针对性的去测试，可以指定一个testid 通过test id 找到 dom 然后测试它的 Placeholder 等值, 正向断言 使用 toBe().....

2023-08-28 06:44 UTC, Xxy1016 requested changes

2023-08-28 06:44 UTC, Xxy1016 commented on packages/nexusgraph-editor/src/Lexical/ui/TextInput.test.tsx
> +    expect(document.getElementsByClassName("Input__label")[0].textContent).toBe("my label");
如果是这种方式 首先要确保 只有一个 className 为 "Input__label" 的 Dom 然后再去获得索引为[0]的Dom再进行后续的断言

2023-08-28 08:16 UTC, Xxy1016 approved these changes

2023-08-28 14:24 UTC, QubitPi requested changes

2023-08-28 14:24 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/ui/TextInput.tsx
> +   * The [placeholder](https://www.w3schools.com/tags/att_input_placeholder.asp) attribute specifies a short hint that describes the expected value of an input field
文档写得非常好！

但我发现另外一个问题：https://github.com/paion-data/nexusgraph/pull/188

2023-09-12 13:38 UTC, closed without merging