Add eslint header for copyright
paion-data/nexusgraph pull request #194
Opened 2023-09-06 05:59 UTC by fannifanni

Changelog
---------

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

* [ ] Test
* [ ] Self-review
* [ ] Documentation

2023-09-06 08:44 UTC, Xxy1016 submitted a review, later dismissed

2023-09-06 10:10 UTC, QubitPi requested changes

2023-09-06 10:10 UTC, QubitPi commented on package.json
> +    "eslint-plugin-header": "latest",
改成具体的版本号

2023-09-07 06:53 UTC, QubitPi approved these changes

2023-09-07 06:54 UTC, Xxy1016 approved these changes

2023-09-07 06:54 UTC, merged