Implement note title input
paion-data/nexusgraph pull request #212
Opened 2023-09-22 02:23 UTC by Xxy1016

Changelog
---------

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

* [ ] Test
* [ ] Self-review
* [ ] Documentation

2023-09-22 03:21 UTC, QubitPi requested changes

2023-09-22 03:21 UTC, QubitPi commented on packages/nexusgraph-app/src/AstraiosClientHook.ts
> +  // }, [noteState, accessToken]);
注释删掉

2023-09-22 03:21 UTC, QubitPi commented on packages/nexusgraph-app/src/AstraiosClientHook.ts
> +    // if(noteState){
注释删掉

2023-09-22 03:21 UTC, QubitPi commented on packages/nexusgraph-editor/src/Editor.tsx
> +      <NoteTitleInput />
考虑放到 Editor 外面

2023-09-22 15:43 UTC, QubitPi requested changes

2023-09-22 15:43 UTC, QubitPi commented on packages/nexusgraph-app/src/AstraiosClientHook.ts
> +  // }, [noteState, accessToken]);
Delete comments

2023-09-22 15:43 UTC, QubitPi commented on packages/nexusgraph-app/src/note-title-input/NoteTitleInput.tsx
> +  const [inputValue, setInputValue] = useState("");
这里的初始标题是空字符串么？为什么之前看到的是 "Note..."

2023-09-22 15:43 UTC, QubitPi commented on packages/nexusgraph-app/src/note-title-input/NoteTitleInput.tsx
> +  const noteList = useSelector((state: GlobalState) => state.noteList);
Redux 在提高代码可维护性上使用了 [encapsulating state shape](https://redux.js.org/usage/deriving-data-selectors#encapsulating-state-shape-with-selectors)，我们需要将所有的 `useSelector` 换成这种形式

2023-09-22 15:43 UTC, QubitPi commented on packages/nexusgraph-app/src/note-title-input/NoteTitleInput.tsx
> +    return note;
这里的逻辑我没看懂，或者说，这样的写法有点奇怪

2023-09-22 15:43 UTC, QubitPi commented on packages/nexusgraph-app/src/note-title-input/NoteTitleInput.tsx
> +  const PencilSquareIcon = (): JSX.Element => <PencilSquareIconSolid />;
用 import 的方式

2023-09-24 03:46 UTC, Xxy1016 commented on packages/nexusgraph-app/src/note-title-input/NoteTitleInput.tsx
> +  const PencilSquareIcon = (): JSX.Element => <PencilSquareIconSolid />;
import 在上方 它本身是一个 `SVGSVGElement` 这里是将它转化为一个 `JSX.Element `

2023-09-24 03:46 UTC, Xxy1016 commented on packages/nexusgraph-app/src/note-title-input/NoteTitleInput.tsx
> +  const [inputValue, setInputValue] = useState("");
本身应该是空的 之前是因为第一条笔记的 titile是"Note..."

2023-09-24 03:46 UTC, Xxy1016 commented on packages/nexusgraph-app/src/note-title-input/NoteTitleInput.tsx
> +    return note;
这里是为了当 input 中的title 更新时，更新列表中的title
```bash
useEffect(() => {
    dispatch(updateNoteTitle(inputValue));
    dispatch(updateNoteList(newList));
  }, [inputValue]);

```

2023-09-24 09:19 UTC, Xxy1016 commented on packages/nexusgraph-app/src/note-title-input/NoteTitleInput.tsx
> +  const [inputValue, setInputValue] = useState("");
这个问题 在 [实现删除和新建笔记的pull request](https://github.com/paion-data/nexusgraph/pull/213)中有改正

2023-09-25 08:44 UTC, QubitPi requested changes

2023-09-25 08:44 UTC, QubitPi commented on hashicorp/images/nginx-ssl-app.conf
> +	listen [::]:30 default_server;
撤回

2023-09-25 08:44 UTC, QubitPi commented on hashicorp/images/nginx-ssl-app.conf
> +	listen 30 default_server;
撤回

2023-09-25 08:44 UTC, QubitPi commented on hashicorp/images/nginx-ssl-app.conf
> +	listen [::]:30 ;
撤回

2023-09-25 08:44 UTC, QubitPi commented on hashicorp/images/nginx-ssl-app.conf
> +	listen 30 ;
撤回

2023-09-25 09:40 UTC, QubitPi requested changes

2023-09-25 09:40 UTC, QubitPi commented on .env.test
> +ENTITY_EXTRACTION_API_URL=http://localhost:5000/entityExtraction
合并一下 `ENTITY_EXTRACTION_API_URL` 和 `EXPAND_API_URL` -> `THERESA_API_URL = http://localhost:5000`，然后在代码里面指定 `expand` 或者 `entityExtration` 即可

2023-09-25 09:40 UTC, QubitPi commented on config/webpack/webpackDevServer.config.js
> +    port: 3000,
👍🏻

2023-09-25 09:40 UTC, QubitPi commented on packages/nexusgraph-redux/src/note/noteDuck.ts
> +  title: "Untitled Note",
i18n

2023-09-25 09:40 UTC, QubitPi commented on packages/nexusgraph-app/src/AstraiosClientHook.ts
> +  const accessToken = selectOAuth().accessToken;
`accessToken` 没有使用了，可以删除

2023-09-25 09:40 UTC, QubitPi commented on packages/nexusgraph-app/src/AstraiosClientHook.ts
>    const noteState: NoteState = selectNote();
`noteState` 没有使用了，可以删除

2023-09-25 09:40 UTC, QubitPi commented on packages/nexusgraph-app/src/ReduxHook.tsx
> +  const noteList = selectNoteList();
`noteList` 没有使用，可以删除

2023-09-26 02:23 UTC, QubitPi approved these changes

2023-09-26 02:23 UTC, QubitPi commented on packages/nexusgraph-graph/src/processor/NodesExpand.ts
> +const THERESA_API_URL_NODE_EXPAND_PARAMETER = "expand/";
我们说 `expand/` 是一个 [path parameter](https://swagger.io/docs/specification/describing-parameters/#path-parameters)，所以 `THERESA_API_URL_NODE_EXPAND_PARAMETER` 可以改成 `NODE_EXPAND_PATH_PARAM`

2023-09-26 02:23 UTC, QubitPi commented on packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.ts
> +const THERESA_API_URL_ENTITY_EXTRACTION_PARAMETER = "entityExtraction/";
`ENTITY_EXTRACTION_PATH_PARAM`

2023-09-26 02:43 UTC, QubitPi approved these changes

2023-09-26 03:04 UTC, merged