Implement note creation and deletion
paion-data/nexusgraph pull request #213
Opened 2023-09-24 09:05 UTC by Xxy1016

Changelog
---------

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

* [ ] Test
* [ ] Self-review
* [ ] Documentation

2023-09-24 13:09 UTC, QubitPi requested changes

2023-09-24 13:09 UTC, QubitPi commented on packages/nexusgraph-app/src/editor-button-group/EditorButtonGroup.tsx
> +    return initialNoteState as Record<any, any>;
这一段逻辑看起来应该是更新删除之后的笔记列表展示，这样以来，这个函数就不仅仅是 delete note 了，很长一段时间之后或者另一位同学来看这段代码，仅从函数名称上是绝对不会想到里面还有更新列表的逻辑的，这会为将来的开发埋下 bug 的隐患

代码逻辑没有问题，然而我有一个完善建议

1. 将 `astraiosClient.deleteNote` 挪出该方法
2. 将方法名称改成 `updateDisplayedNoteList`

2023-09-24 13:09 UTC, QubitPi commented on packages/nexusgraph-app/src/editor-button-group/EditorButtonGroup.tsx
> +function selectedNote(noteId: string) {
`fetchNoteById` 会更好，`selectedNote` 很难让人理解这个函数在做什么，因为 `selectedNote` 在英语里面是一个**名词结构**，函数的命名应该用**动词结构**，请记住，工业界代码，可读性和可维护性是重中之重

2023-09-24 13:20 UTC, Xxy1016 commented on packages/nexusgraph-editor/src/Lexical/plugins/EditorInitializationPlugin.ts
> +  }, [note.id]);
这段逻辑是为了实现切换笔记时 重新 `setEditorState`

2023-09-25 01:54 UTC, QubitPi approved these changes
👍🏻

2023-09-25 01:54 UTC, QubitPi commented on packages/nexusgraph-app/src/editor-button-group/EditorButtonGroup.tsx
> +                    });
👍🏻

2023-09-25 01:54 UTC, merged