Imperfect implementation
paion-data/nexusgraph pull request #221
Opened 2023-10-08 10:28 UTC by Xxy1016

Changelog
---------

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

* [ ] Test
* [ ] Self-review
* [ ] Documentation

2023-10-10 12:50 UTC, QubitPi requested changes

2023-10-10 12:50 UTC, QubitPi commented on package.json
> +    "react-bootstrap": "^2.9.0",
这算是个巧合吧

虽然官方文档说还要安装 [`bootstrap`](https://react-bootstrap.netlify.app/docs/getting-started/introduction#installation)，但它提到了一个前提：

> If you plan on customizing the Bootstrap Sass files, or don't want to use a CDN for the stylesheet, it may be helpful to install [vanilla Bootstrap](https://getbootstrap.com/docs/5.3/getting-started/download/#npm) as well.

也就是说如果我们用 styled-components 定义我们自己的 CSS 的话，是可以不装 `bootstrap` 的。所以你之前没有装 `bootstrap` 反倒是正确的

2023-10-10 12:50 UTC, QubitPi commented on packages/nexusgraph-app/src/ReduxHook.tsx
> +  const intelligentAIState: string | null = selectIntelligentAI();
变量名称可以优化一下

`intelligentAIState` -> `initialGraphText`

2023-10-10 12:50 UTC, QubitPi commented on packages/nexusgraph-app/src/sidebar/CreateButton.tsx
> +  const [show, setShow] = useState(false);
`show` 放在 `CreateButton` 容易让人理解成是 button 的 show；同时为了我们后续的 debug，建议改成 `modalShown`

2023-10-10 12:50 UTC, QubitPi commented on packages/nexusgraph-app/src/sidebar/CreateButton.tsx
> +  const handleShow = () => setShow(true);
setShow(true); 可以放进 `showModal`，简化下面的 callback 逻辑

2023-10-10 12:59 UTC, QubitPi requested changes

2023-10-10 12:59 UTC, QubitPi commented on packages/nexusgraph-nlp/src/processor/NaturalLanguageProcessor.ts
> +  entityExtraction(editorLines: string): Promise<Graph>;
这里因为什么改成了 string?

2023-10-10 13:04 UTC, QubitPi requested changes

2023-10-10 13:04 UTC, QubitPi commented on packages/nexusgraph-app/src/sidebar/useModal.tsx
> +    closeOnClickOutside: boolean;
以我对 modal 的理解，`closeOnClickOutside` 永远应该是 `true`，所以看看有没有必要传这个参数

而且 modalContent 从可读性上讲，也只应包含 `content: JSX.Element;`，语义上才好理解

2023-10-10 13:04 UTC, QubitPi commented on packages/nexusgraph-app/src/sidebar/useModal.tsx
> +  const modal = useMemo(() => {
在这里 `useMemo` 的好处是什么？<img src="https://github.com/paion-data/nexusgraph/assets/16126939/453e339b-c7f1-4841-98df-e14cb7c6c4aa" width="60px"/>

2023-10-10 13:04 UTC, QubitPi commented on packages/nexusgraph-app/src/sidebar/useModal.tsx
> +    }
这个 if 有点奇怪，为什么不直接 `return modalContent` ?

2023-10-10 13:29 UTC, QubitPi commented on packages/nexusgraph-app/src/sidebar/Modal.tsx
> +    <ModalOverlay id={"modal"} show={show} onHide={handleClose} role="dialog">
ModalOverlay 看起来应该是 react-bootstrap Modal 的封装，在之上添加了 CSS 风格，Overlay 这个词是“叠加”的意思，可以理解成是 CSS 的叠加，没问题，但没能特别体现“react-bootstrap Modal 的封装”的含义，`StyledModal` 会不会更好

2023-10-10 13:29 UTC, QubitPi commented on packages/nexusgraph-app/src/sidebar/Modal.tsx
> +      <ModalWapper>
为什么 ModalWapper 会被包在里面？ModalWapper 和 ModalOverlay 合并貌似更加适合 `ModalOverlay` 的存在

2023-10-10 13:35 UTC, QubitPi requested changes
**逻辑上我找到了几处要完善的地方，但既然你想先再改改，我就先不妨碍你的思路，明天来了我们再看**

2023-10-11 03:41 UTC, Xxy1016 commented on packages/nexusgraph-nlp/src/processor/NaturalLanguageProcessor.ts
> +  entityExtraction(editorLines: string): Promise<Graph>;
原先传的是 Lexical 的 `editorState` 现在直接传递 `Modal` 中 文本框的内容，所以直接改成了 `string`

2023-10-11 03:45 UTC, Xxy1016 commented on packages/nexusgraph-app/src/sidebar/useModal.tsx
> +  const modal = useMemo(() => {
这里是一个性能优化，只有在Modal的内容发生变化 或关闭Modal时 才会重新计算 `modal`的值，而不必在每次页面渲染时都计算  `modal` ，这样可以节省内存

2023-10-11 03:54 UTC, Xxy1016 commented on packages/nexusgraph-app/src/sidebar/useModal.tsx
> +    }
原来的 `modalContent` 并不完全是一个JSX.Element：
```bash
   modalContent ={
      closeOnClickOutside: boolean;
      content: JSX.Element;
  }
```

并且语义不同，`modalContent`  是 `Modal` 组件的 `children` ，而这里定义的 `modal` 变量，应该是 **`Modal` 组件**或是一个**空的组件**

2023-10-11 04:03 UTC, Xxy1016 commented on packages/nexusgraph-app/src/sidebar/Modal.tsx
> +      <ModalWapper>
`ModalWapper` 实际上定义了一个`Div` 封装 modal 的内容，已经更名为 `StyledModalContent`

2023-10-11 06:11 UTC, closed without merging