Implement remote nlp processor
paion-data/nexusgraph pull request #97
Opened 2023-07-05 03:48 UTC by fannifanni

Changelog
---------

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

* [ ] Test
* [ ] Self-review
* [ ] Documentation

2023-07-05 04:24 UTC, Xxy1016 commented on packages/messier-61-graph/src/Graph.tsx
注释可以删掉，eslint检查不允许这种行内注释

2023-07-05 04:34 UTC, Xxy1016 commented on packages/messier-61-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
> +    let arr: BasicNode[] = [];
工业化的代码， 每个变量的命名都必须是有意义的，例如：`editorLines`，可以让我们光看名字就知道这个变量是用来定义哪些数据的， arr我觉得可以改成`InitialNodes`，如果你有更好的名字也可以，因为我一直不太会起名😁

2023-07-06 03:25 UTC, Xxy1016 approved these changes

2023-07-06 03:42 UTC, Xxy1016 submitted a review, later dismissed

2023-07-06 04:17 UTC, Xxy1016 approved these changes

2023-07-06 05:22 UTC, QubitPi requested changes
不错，基本功能已经实现 👍🏻

2023-07-06 05:22 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
> +        console.log(err);
工业界代码不会出现 `console.log` 这样的语句，我会将 sentry 系统搭建出来，然后在这里将报错[发送给我们的日志监控系统](https://docs.sentry.io/platforms/javascript/guides/react/usage/)，
这里可以暂时写成这样

2023-07-06 05:22 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
> +      .get(rootUrl + "sentence=" + editorLines)
- 变量绝不超出最小使用范围，`rootUrl` 只在 axios 里使用就维护[变量 scope 最小原则](https://refactoring.com/catalog/reduceScopeOfVariable.html)，放在 axios scope 里
- 代码尽可能简洁
- `.get(rootUrl + "sentence=" + editorLines)` 的拼接写法[原则上是不安全的](https://owasp.org/www-community/attacks/Web_Parameter_Tampering)

可以直接改成 

```typescript
    .get(
      "https://machine-learning.paion-data.dev/entityExtraction",
      {
        params: {
          sentence: editorLines.join(" ")
        }
      }
    )
```

2023-07-06 05:22 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
> +  getBasicNode(data: any) {
方法之间要空一行

2023-07-06 05:22 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
> +import { BasicNode } from "../../../../nexusgraph-graph/src/Graph";
在 [index.ts](https://github.com/paion-data/nexusgraph/blob/master/packages/nexusgraph-graph/index.ts) 里加入

```typescript
export type { BasicNode } from "./src/Graph";
```

这里的 import 就[简化](https://stackoverflow.com/a/37564980)成

```typescript
import { BasicNode } from "../../../../nexusgraph-graph";
```

2023-07-06 07:22 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.test.ts
> +test("Returns an empty 'nodes' and 'relationships' with no input from the user", () => {
import 和 test 之间要有一个空行

工业界代码看重

- 可读性（本例）
- 可维护性

后续的开发我们会教你体会这两点的重要性

2023-07-06 07:22 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
> +    // let rootUrl = "https://machine-learning.paion-data.dev/entityExtraction?";
注释可以删掉

2023-07-06 07:22 UTC, QubitPi commented on packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
> +    let basicNodes: BasicNode[] = [];
`const`

2023-07-06 07:33 UTC, QubitPi approved these changes

2023-07-06 07:34 UTC, QubitPi approved these changes
👍🏻

2023-07-06 07:59 UTC, Xxy1016 approved these changes

2023-07-06 09:29 UTC, merged